[tool.poetry]
name = "ntt-project"
version = "0.1.0"
description = ""
authors = ["Fabion Toci <toci.fabion.nttdata@skytv.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
